language: ruby

rvm:
 - 2.6.3

addons:
  postgresql: "9.5"

env:
  global:
    - BUNDLE_GEMFILE="$TRAVIS_BUILD_DIR/Gemfile"
    - BUNDLE_PATH="$HOME/.bundle"
  matrix:
    - GEM=. DB=postgres

script:
  - cd $GEM;
  - bundle exec rake test_app
  - SIMPLECOV=1 CODECOV=1 bundle exec rake
